### ISSUE TITLE
run-tme wrong path

### ISSUE THREAD

**Issue by asmithrsa** [ambiamber/Run-Sun3-SunOS-4.1.1#1]
run-tme seems to have the LTLD_LIBRARY_PATH different from the repo

**Comment by ambiamber** [comment]
README.md has

```
./configure --disable-shared --disable-warnings --enable-ltdl-install --prefix=/opt/tme # or use --prefix= set to some other directory
```
So `--prefix=/opt/tme` will create `/opt/tme/lib` which is what is in `run-tme`.

Did I miss anything else?

**Comment by ambiamber** [comment]
I added another section header to indicate that `./configure ...` is not an Arch Linux thing.

**Comment by asmithrsa** [comment]
> I added another section header to indicate that `./configure ...` is not an Arch Linux thing.

Thank you that's more clear
